Add fail_if_[alias|function]_defined helpers

diff --git a/test/test_util b/test/test_util
--- a/test/test_util
+++ b/test/test_util
@@ -25,6 +25,15 @@ function fail_if_var_not_set() {
     fi
 }
 
+function fail_if_function_defined() {
+    if type "$1"; then
+        echo "Error: '$1' is defined, but shouldn't be:" `type "$1"`
+        exit 1
+    fi
+}
+
+alias fail_if_alias_defined='fail_if_function_defined'
+
 function emgr_setup() {
     source "$TEST_DIR/../emgr_setup"
 }
